package com.teayork.module_main.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.teayork.module_main.daobean.User;
import com.teayork.module_main.daobean.CommunityBean;
import com.teayork.module_main.daobean.HotBean;

import com.teayork.module_main.dao.UserDao;
import com.teayork.module_main.dao.CommunityBeanDao;
import com.teayork.module_main.dao.HotBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userDaoConfig;
    private final DaoConfig communityBeanDaoConfig;
    private final DaoConfig hotBeanDaoConfig;

    private final UserDao userDao;
    private final CommunityBeanDao communityBeanDao;
    private final HotBeanDao hotBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        communityBeanDaoConfig = daoConfigMap.get(CommunityBeanDao.class).clone();
        communityBeanDaoConfig.initIdentityScope(type);

        hotBeanDaoConfig = daoConfigMap.get(HotBeanDao.class).clone();
        hotBeanDaoConfig.initIdentityScope(type);

        userDao = new UserDao(userDaoConfig, this);
        communityBeanDao = new CommunityBeanDao(communityBeanDaoConfig, this);
        hotBeanDao = new HotBeanDao(hotBeanDaoConfig, this);

        registerDao(User.class, userDao);
        registerDao(CommunityBean.class, communityBeanDao);
        registerDao(HotBean.class, hotBeanDao);
    }
    
    public void clear() {
        userDaoConfig.clearIdentityScope();
        communityBeanDaoConfig.clearIdentityScope();
        hotBeanDaoConfig.clearIdentityScope();
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public CommunityBeanDao getCommunityBeanDao() {
        return communityBeanDao;
    }

    public HotBeanDao getHotBeanDao() {
        return hotBeanDao;
    }

}
